merge recent upstream (#2)
* Take semver-compatible deps

* generate.py: reformat for black 2026.1.0

* build(deps): bump taiki-e/cache-cargo-install-action from 2 to 3

Bumps [taiki-e/cache-cargo-install-action](https://github.com/taiki-e/cache-cargo-install-action) from 2 to 3.
- [Release notes](https://github.com/taiki-e/cache-cargo-install-action/releases)
- [Changelog](https://github.com/taiki-e/cache-cargo-install-action/blob/main/CHANGELOG.md)
- [Commits](https://github.com/taiki-e/cache-cargo-install-action/compare/v2...v3)

---
updated-dependencies:
- dependency-name: taiki-e/cache-cargo-install-action
  dependency-version: '3'
  dependency-type: direct:production
  update-type: version-update:semver-major
...

Signed-off-by: dependabot[bot] <support@github.com>

* fix rust 1.94 ambiguous panic macro warnings

```
error: `panic` is ambiguous
   --> src/./alg_tests.rs:699:26
    |
699 |             unhandled => panic!("extend der2text for tag 0x{unhandled:x?}"),
    |                          ^^^^^ ambiguous name
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #147319 <https://github.com/rust-lang/rust/issues/147319>
    = note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
```

* avoid std::prelude imports

This also means the panic macro isn't ambiguous so we can drop explicit
panic imports.

* crl: fix authoritative_for() support for multiple URIs

* Prepare 0.103.10

* Allow parsing trust anchors with unknown criticial extensions

* Bump version to 0.103.11

* Rewrite constraint matching to avoid permissive catch-all branch

* Ignore wildcard labels when matching name constraints

* Clean up stuttery enum variant names

* Bump version to 0.103.12

* Actually fail closed for URI matching against excluded subtrees

* Correct validation of BIT STRING constraints

* Improve tests for padding of `BitStringFlags`

* Prepare 0.103.13

* crl: fix clippy::question_mark finding

Of the form:

```
error: this `match` expression can be replaced with `?`
   --> src/crl/types.rs:357:13
    |
357 | /             match revoked_cert_result {
358 | |                 Err(e) => return Err(e),
359 | |                 Ok(revoked_cert) => {
360 | |                     if revoked_cert.serial_number.eq(serial) {
...   |
364 | |             }
    | |_____________^
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/rust-1.97.0/index.html#question_mark
    = note: `-D clippy::question-mark` implied by `-D warnings`
    = help: to override `-D warnings` add `#[allow(clippy::question_mark)]`
```

* ci: sync cargo-check-external-types nightly

* Upgrade to base64 0.23

* Update to aws-lc-rs 1.18

* Support stable ML-DSA with aws-lc-rs

* Bump version to 0.103.14

* Mark ML-DSA algorithms as FIPS submitted

* post-upstream sync fix

* post-upstream sync fix 2

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Joe Birr-Pixton <jpixton@gmail.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Daniel McCarney <daniel@binaryparadox.net>
Co-authored-by: Dirkjan Ochtman <dirkjan@ochtman.nl>